create database EMPRESA;

CREATE TABLE `EMPRESA`(
	`CNPJ` INT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(150) DEFAULT NULL,
    `TELEFONE` VARCHAR(150) DEFAULT NULL,
    `ENDERECO` VARCHAR(150) DEFAULT NULL,
    `email` VARCHAR (150) DEFAULT NULL,
    `site` VARCHAR(150) DEFAULT NULL,
    PRIMARY KEY (`CNPJ`));
    
    
    

CREATE TABLE `VAGA`(
	`ID` INT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(150) DEFAULT NULL,
    `DESCRICAO` VARCHAR(150) DEFAULT NULL,
    `NUMERO` VARCHAR(150) DEFAULT NULL,
    `SALARIO` VARCHAR (150) DEFAULT NULL,
    `BENEFICIO` VARCHAR(150) DEFAULT NULL,
    `REQUISITOS` VARCHAR(150) DEFAULT NULL,
    `STATUS` VARCHAR(150) DEFAULT NULL,
    PRIMARY KEY (`ID`));
    


